@ConfigurablePdfApi_HostAddress = http://localhost:5108

### Generowanie z Html
POST {{PdfApi_HostAddress}}/generate
Accept: application/json
Content-Type: application/json

{ "Html" : "Hello world!" }