@ConfigurablePdfApi_HostAddress = http://localhost:5108

### Generowanie z Html
POST {{ConfigurablePdfApi_HostAddress}}/generate
Accept: application/json
Content-Type: application/json

{ "Html" : "<html><body><h1>Hello World!</h1></body></html>" }