//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Samples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp2.Samples.HtmlTemplates", typeof(HtmlTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt;Invoice #0001&lt;/title&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      font-family: Arial, Helvetica, sans-serif;
        ///      margin: 0;
        ///      padding: 0;
        ///      background: #f5f5f5;
        ///    }
        ///
        ///    .invoice-box {
        ///      max-width: 800px;
        ///      margin: 40px auto;
        ///      padding: 30px;
        ///      border: 1px solid #eee;
        ///      background: #fff;
        ///      box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        ///    }
        ///
        ///    .invoice-box table {
        ///      width: 100%;
        ///      line-height: inherit;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvoiceTemplate {
            get {
                return ResourceManager.GetString("InvoiceTemplate", resourceCulture);
            }
        }
    }
}
